import pickle

# # Step 1: tools.pkl file ko read karein
# with open('tools.pkl', 'rb') as file:
#     display_data = pickle.load(file)

# # Step 2: Read kiye gaye data ko .txt file mein save karein
# with open('tools_data.txt', 'w', encoding='utf-8') as txt_file:
#     txt_file.write(str(display_data))

# print("tools.pkl ka data successfully 'tools_data.txt' mein save ho gaya hai.")

